//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace JustEat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string FoodName { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPrice { get; set; }
        public int FoodId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> RestaurentId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Food Food { get; set; }
        public virtual Order Order { get; set; }
        public virtual Restaurent Restaurent { get; set; }
    }
}
