//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace JustEat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Carts = new HashSet<Cart>();
            this.CustomerNotifications = new HashSet<CustomerNotification>();
            this.Notifications = new HashSet<Notification>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public System.DateTime PlacedTime { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<System.DateTime> DeliveredTime { get; set; }
        public double Ammount { get; set; }
        public int CustomerId { get; set; }
        public string Status { get; set; }
        public string Readed { get; set; }
        public Nullable<int> RestaurentId { get; set; }
        public Nullable<int> DeliveryManId { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> FinalAmmount { get; set; }
        public Nullable<int> DeliveryFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerNotification> CustomerNotifications { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Restaurent Restaurent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
