//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace JustEat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public int RestaurentProfit { get; set; }
        public int JEProfit { get; set; }
        public int DeliveryManProfit { get; set; }
        public int CustomerId { get; set; }
        public int OrderId { get; set; }
        public int RestaurentId { get; set; }
        public int DeliveryManId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual Order Order { get; set; }
        public virtual Restaurent Restaurent { get; set; }
    }
}
